ubuntu:
	python ../post.py ubuntu-on-mac.txt 240272

eeepc:
	python ../post.py eeepc.txt 240841

eeepc-ubuntu:
	python ../post.py eeepc-ubuntu.txt 246386

eeepc-main:
	python ../post.py eeepc-as-main-box.txt 257325

caring:
	python ../post.py caring.txt 259296 

eurolisp2:
	python ../post.py eurolisp2.txt 259505

europython2010:
	python ../post.py europython2010.txt 293373
