ubuntu:
	python2.5 ../post.py ubuntu-on-mac.txt 240272

eeepc:
	python2.5 ../post.py eeepc.txt 240841

eeepc-ubuntu:
	python2.5 ../post.py eeepc-ubuntu.txt 246386

eeepc-main:
	python2.5 ../post.py eeepc-as-main-box.txt 257325
