POST = python2.5 ../post.py
MINIDOC = python2.5 ~/trunk/ROnline/RCommon/Python/ms/tools/minidoc.py

default:
	echo "Available python files:"; ls *.py

scheme1: scheme1.txt
	rst scheme1.txt; $(POST) scheme1.txt 238789

scheme2: scheme2.txt
	rst scheme2.txt; $(POST) scheme2.txt 238941

scheme3: scheme3.txt
	rst scheme3.txt; $(POST) scheme3.txt 239466

scheme4: scheme4.txt
	rst scheme4.txt; $(POST) scheme4.txt 239568

scheme5: scheme5.txt
	rst scheme5.txt; $(POST) scheme5.txt 239699

scheme6: scheme6.txt
	$(POST) scheme6.txt 240198

