POST = python ../post.py
RST = python ~/trunk/ROnline/RCommon/Python/ms/tools/rst.py
MINIDOC = python ~/trunk/ROnline/RCommon/Python/ms/tools/minidoc.py

ii:	interfaces-vs-inheritance.txt
	$(RST) interfaces-vs-inheritance.txt; $(POST) interfaces-vs-inheritance.txt 274019
