upload:
	python make_sweet_macros.py
	zip -r aps aps/README.txt sweet-macros aps/compat.ikarus.sls aps/compat.ypsilon.sls aps/cut.sls aps/easy-test.sls aps/list-utils.sls aps/repeat.sls
	#scp aps.zip merlin.phyast.pitt.edu:public_html/scheme
