upload:
	#python make_sweet_macros.py
	zip -r aps aps/README.txt aps/compat.ikarus.sls aps/compat.ypsilon.sls aps/compat.mzscheme.sls aps/cut.sls aps/easy-test.sls aps/list-utils.sls aps/repeat.sls
	scp aps.zip micheles@merlin.phyast.pitt.edu:public_html/scheme
experimental.zip:
	zip -r experimental experimental/mod?.sls
