count:
	wc -l __init__.py automatize.py configurator.py connection.py \
	mssql_support.py postgres_support.py sqlite_support.py \
	mssql_util.py postgres_util.py sqlite_util.py \
        sql_support.py uri.py util.py table.py runtransac.py memoize.py 
